# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
