# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 2, 19, 31, 16, 270434, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 19, 31, 35, 492403, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
